// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD35HDRKA3gVaBU-8A0nR83lqtPqiYwpUQ',
    appId: '1:911750043532:web:589198231d5e1f45d2a8a9',
    messagingSenderId: '911750043532',
    projectId: 'online-marketing-app-a716a',
    authDomain: 'online-marketing-app-a716a.firebaseapp.com',
    storageBucket: 'online-marketing-app-a716a.firebasestorage.app',
    measurementId: 'G-YJP0XNTK0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbiHeJw9My1V64g6aYBg_O19oIBZWyTcY',
    appId: '1:911750043532:android:9a1694c1748b3f50d2a8a9',
    messagingSenderId: '911750043532',
    projectId: 'online-marketing-app-a716a',
    storageBucket: 'online-marketing-app-a716a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-GD50Ljx6BudAeVIjw2-SOhRJZd6DJxs',
    appId: '1:911750043532:ios:90b18fa47b75c2fdd2a8a9',
    messagingSenderId: '911750043532',
    projectId: 'online-marketing-app-a716a',
    storageBucket: 'online-marketing-app-a716a.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-GD50Ljx6BudAeVIjw2-SOhRJZd6DJxs',
    appId: '1:911750043532:ios:90b18fa47b75c2fdd2a8a9',
    messagingSenderId: '911750043532',
    projectId: 'online-marketing-app-a716a',
    storageBucket: 'online-marketing-app-a716a.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD35HDRKA3gVaBU-8A0nR83lqtPqiYwpUQ',
    appId: '1:911750043532:web:480826142400250dd2a8a9',
    messagingSenderId: '911750043532',
    projectId: 'online-marketing-app-a716a',
    authDomain: 'online-marketing-app-a716a.firebaseapp.com',
    storageBucket: 'online-marketing-app-a716a.firebasestorage.app',
    measurementId: 'G-B0RMWERMX3',
  );
}
